services:
  stats-db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  stats-server:
    build: ./stats-module/stats-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy

  ewm-db:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-service:
    build: ./main-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      STATS_SERVER_URL: http://stats-server:9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/main_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db